# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - run: sudo su
    - run: cd /var/www/apps/starter-node
    - run: git pull
    - run: npm install
    - run: sequelize db:migrate
    - run: pm2 restart starter-node
