# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: SSH and pull data
        working-directory: /var/www/apps/starter-node
        run: |
          git pull
          npm install
          sequelize db:migrate
          pm2 restart starter-node
